//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3082
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BubbleBobble {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BubbleBobble.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bobc1 {
            get {
                object obj = ResourceManager.GetObject("bobc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobc1i {
            get {
                object obj = ResourceManager.GetObject("bobc1i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobc2 {
            get {
                object obj = ResourceManager.GetObject("bobc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobc2i {
            get {
                object obj = ResourceManager.GetObject("bobc2i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobc3 {
            get {
                object obj = ResourceManager.GetObject("bobc3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobc3i {
            get {
                object obj = ResourceManager.GetObject("bobc3i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobfte {
            get {
                object obj = ResourceManager.GetObject("bobfte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobm1 {
            get {
                object obj = ResourceManager.GetObject("bobm1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobm2 {
            get {
                object obj = ResourceManager.GetObject("bobm2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobm3 {
            get {
                object obj = ResourceManager.GetObject("bobm3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bobm4 {
            get {
                object obj = ResourceManager.GetObject("bobm4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubc1 {
            get {
                object obj = ResourceManager.GetObject("bubc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubc1i {
            get {
                object obj = ResourceManager.GetObject("bubc1i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubc2 {
            get {
                object obj = ResourceManager.GetObject("bubc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubc2i {
            get {
                object obj = ResourceManager.GetObject("bubc2i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubc3 {
            get {
                object obj = ResourceManager.GetObject("bubc3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubc3i {
            get {
                object obj = ResourceManager.GetObject("bubc3i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubcm {
            get {
                object obj = ResourceManager.GetObject("bubcm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubfte {
            get {
                object obj = ResourceManager.GetObject("bubfte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubm1 {
            get {
                object obj = ResourceManager.GetObject("bubm1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubm2 {
            get {
                object obj = ResourceManager.GetObject("bubm2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubm3 {
            get {
                object obj = ResourceManager.GetObject("bubm3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bubm4 {
            get {
                object obj = ResourceManager.GetObject("bubm4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bv {
            get {
                object obj = ResourceManager.GetObject("bv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bvd1 {
            get {
                object obj = ResourceManager.GetObject("bvd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bvd2 {
            get {
                object obj = ResourceManager.GetObject("bvd2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bvd3 {
            get {
                object obj = ResourceManager.GetObject("bvd3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bvd4 {
            get {
                object obj = ResourceManager.GetObject("bvd4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bvr1 {
            get {
                object obj = ResourceManager.GetObject("bvr1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bvr2 {
            get {
                object obj = ResourceManager.GetObject("bvr2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icono {
            get {
                object obj = ResourceManager.GetObject("icono", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;vvvv&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;vvvv&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;vvvv&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;^^^^&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xxxx^^^xxxxxxxxxxxxxxxxxx^^^xxxx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string n0001 {
            get {
                return ResourceManager.GetString("n0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;vvvv&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;vvvv&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;vvvv&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;^^^^&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx^^^^^^^^^^^xxxxxx^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^xxxxx^^xxxxx^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string n0002 {
            get {
                return ResourceManager.GetString("n0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xxxxxxxxx^^^^xxxxxx^^^^xxxxxxxxx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;vvvv&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;vvvv&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;xx
        ///xx^^^^^^^^^^^^vvvv^^^^^^^^^^^^xx
        ///xx^^^^^^^^^^^^^^^^^^^^^^^^^^^^xx
        ///xx^^^xxxxxxxx&gt;^^^^&lt;xxxxxxxx^^^xx
        ///xx^^^x&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;^^^^&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;x^^^xx
        ///xx^^^x&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;^^^^&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;x^^^xx
        ///xx^^^x&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;^^^^&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;x^^^xx
        ///xx^^^x&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;^^^^&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;x^^^xx
        ///xx^^^xxxxxxxxx&gt;^^&lt;xxxxxxxxx^^^xx
        ///xx^^^x&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;^^&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;x^^^xx
        ///xx^^^x&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;^^&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;x^^^xx
        ///xx^^^x^^^^^^^^^^^^^^^^^^^^x^^^xx
        ///xx^^^x^^^^^^^^^^^^^^^^^^^^x^^^xx
        ///xx [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string n0003 {
            get {
                return ResourceManager.GetString("n0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xxxxxxxxxvvvvxxxxxxvvvvxxxxxxxxx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xxvvx^^^^^^^^^^^^^^^^^^^^^^xvvxx
        ///xx^^xxxxxxxxxxxxxxxxxxxxxxxx^^xx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xxvvvvxxvvvvvvvvvvvvvvvvxxvvvvxx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xxvvvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xx^vvvvvvvvvvvvvvvvvvvvvvvvvvvxx
        ///xx [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string n0063 {
            get {
                return ResourceManager.GetString("n0063", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap pared01 {
            get {
                object obj = ResourceManager.GetObject("pared01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pared2 {
            get {
                object obj = ResourceManager.GetObject("pared2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pared3 {
            get {
                object obj = ResourceManager.GetObject("pared3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pared4 {
            get {
                object obj = ResourceManager.GetObject("pared4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pared5 {
            get {
                object obj = ResourceManager.GetObject("pared5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap renc {
            get {
                object obj = ResourceManager.GetObject("renc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap renc1 {
            get {
                object obj = ResourceManager.GetObject("renc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap renc2 {
            get {
                object obj = ResourceManager.GetObject("renc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rt0 {
            get {
                object obj = ResourceManager.GetObject("rt0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rt0i {
            get {
                object obj = ResourceManager.GetObject("rt0i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rt1 {
            get {
                object obj = ResourceManager.GetObject("rt1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rt1i {
            get {
                object obj = ResourceManager.GetObject("rt1i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rt2 {
            get {
                object obj = ResourceManager.GetObject("rt2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rt2i {
            get {
                object obj = ResourceManager.GetObject("rt2i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rt3 {
            get {
                object obj = ResourceManager.GetObject("rt3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rt3i {
            get {
                object obj = ResourceManager.GetObject("rt3i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rtf {
            get {
                object obj = ResourceManager.GetObject("rtf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vi1 {
            get {
                object obj = ResourceManager.GetObject("vi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vi2 {
            get {
                object obj = ResourceManager.GetObject("vi2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vi3 {
            get {
                object obj = ResourceManager.GetObject("vi3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vi4 {
            get {
                object obj = ResourceManager.GetObject("vi4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienc {
            get {
                object obj = ResourceManager.GetObject("vienc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienc1 {
            get {
                object obj = ResourceManager.GetObject("vienc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienc2 {
            get {
                object obj = ResourceManager.GetObject("vienc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vif {
            get {
                object obj = ResourceManager.GetObject("vif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vii1 {
            get {
                object obj = ResourceManager.GetObject("vii1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vii2 {
            get {
                object obj = ResourceManager.GetObject("vii2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vii3 {
            get {
                object obj = ResourceManager.GetObject("vii3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vii4 {
            get {
                object obj = ResourceManager.GetObject("vii4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
